version: "3.9"
services:
 vite_docker:
   image: node:19
   container_name: geomap_docker
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true